name = "ChunkSplitters"
uuid = "ae650224-84b6-46f8-82ea-d812ca08434e"
authors = ["Leandro Martinez <lmartine@unicamp.br> and contributors"]
version = "0.1.0"

[deps]
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
julia = "1"
TestItems = "0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner"]
